jenkins_plugins:
  - ace-editor
  - ansible
  - ant
  - antisamy-markup-formatter
  - apache-httpcomponents-client-4-api
  - bootstrap4-api
  - bouncycastle-api
  - parameterized-trigger
  - branch-api
  - build-pipeline-plugin
  - build-timeout
  - checks-api
  - cloudbees-folder
  - command-launcher
  - conditional-buildstep
  - credentials
  - credentials-binding
  - delivery-pipeline-plugin
  - display-url-api
  - durable-task
  - echarts-api
  - email-ext
  - emailext-template
  - font-awesome-api
  - git
  - git-client
  - github
  - github-api
  - github-branch-source
  - git-server
  - gradle
  - handlebars
  - jackson2-api
  - javadoc
  - jdk-tool
  - job-dsl
  - jquery
  - jquery3-api
  - jsch
  - junit
  - ldap
  - lockable-resources
  - mailer
  - matrix-auth
  - matrix-project
  - maven-plugin
  - momentjs
  - okhttp-api
  - pam-auth
  - pipeline-build-step
  - pipeline-github-lib
  - pipeline-graph-analysis
  - pipeline-input-step
  - pipeline-milestone-step
  - pipeline-model-api
  - pipeline-model-definition
  - pipeline-model-extensions
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-tags-metadata
  - pipeline-stage-view
  - plain-credentials
  - plugin-util-api
  - popper-api
  - resource-disposer
  - run-condition
  - scm-api
  - script-security
  - snakeyaml-api
  - ssh
  - ssh-credentials
  - ssh-slaves
  - structs
  - timestamper
  - token-macro
  - trilead-api
  - webhook-step
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps
  - workflow-cps-global-lib
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - ws-cleanup